version: "3"

services:

  chrome:
    image: selenium/node-chrome:4.9.0-20230421
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - 5900:5900
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
      - ./data:/app/data

  selenium-hub:
    image: selenium/hub:4.9.0-20230421
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    volumes:
      - ./downloads:/home/seluser/Downloads

  trxuitest:
      container_name: trxuitest
      build: 
        context: .
        no_cache: true
      links:
        - selenium-hub
        - chrome
      volumes:
        - ./downloads:/app/downloads
        - ./data:/app/data
        - ./TestResults:/app/TestResults